/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package edutrack;

import java.awt.Image;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Admins
 */
public class dangnhap extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    mysql connect = new mysql();
    public dangnhap() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    public String check_id()
    {
        String user_id;
        String username = txtDangnhap.getText();
        String pass = new String(txtPass.getPassword());
        String sql_login = "select UserID from TAIKHOAN WHERE Username = ? and Pass = ? ";
        try {
            PreparedStatement pst = connect.conn.prepareStatement(sql_login);
            pst.setString(1, username);
            pst.setString(2, pass);
            ResultSet rs = pst.executeQuery();
            if(rs.next())
            {
                user_id = rs.getString("UserID");
                return user_id;
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this,"Lỗi querry");
        }
        return "";
    }
    public int login()
    {
        int role_id;
        String username = txtDangnhap.getText();
        String pass = new String(txtPass.getPassword());
        String sql_login = "select * from TAIKHOAN WHERE Username = ?";
        try {
            PreparedStatement pst = connect.conn.prepareStatement(sql_login);
            pst.setString(1, username);
            ResultSet rs = pst.executeQuery();
            if(rs.next())
            {
                if(!rs.getString("username").equals(username))
                {
                    JOptionPane.showMessageDialog(this,"Tài khoản không tồn tại");
                    return 0;
                }
                else if(!rs.getString("pass").equals(pass))
                {
                    JOptionPane.showMessageDialog(this,"Sai mật khẩu");
                    return 0;
                }
                role_id = rs.getInt("RoleID");
                return role_id;
            }
            else 
                return 0;
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this,"Lỗi querry");
        }
        return 0;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtDangnhap = new javax.swing.JTextField();
        txtPass = new javax.swing.JPasswordField();
        jButtondangnhap = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        check_show = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Tài khoản");

        jLabel4.setText("Mật khẩu");

        jButtondangnhap.setText("Đăng nhập");
        jButtondangnhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtondangnhapActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(102, 204, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Đăng nhập");
        jLabel1.setToolTipText("");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setOpaque(true);

        check_show.setText("Hiện mật khẩu");
        check_show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check_showActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtDangnhap, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                    .addComponent(txtPass))
                .addGap(52, 52, 52))
            .addGroup(layout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(check_show)
                    .addComponent(jButtondangnhap, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtDangnhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(check_show)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtondangnhap)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtondangnhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtondangnhapActionPerformed
        int role_id = login();
        String user_id = check_id();
        switch (role_id)
        {
            case 1:
                JOptionPane.showMessageDialog(this, "Đăng nhập thành công","thành công",JOptionPane.INFORMATION_MESSAGE);
                NhanVien b = new  NhanVien(user_id);
                b.setVisible(true);
                this.dispose();
                break;
            case 2:
            {
                JOptionPane.showMessageDialog(this, "Đăng nhập thành công","thành công",JOptionPane.INFORMATION_MESSAGE);
                giaovien c = new giaovien(user_id);
                c.setVisible(true);
                this.dispose();
                break;
            }
            case 3:
            {
                JOptionPane.showMessageDialog(this, "Đăng nhập thành công","thành công",JOptionPane.INFORMATION_MESSAGE);
                hocvien a = new  hocvien(user_id);
                a.setVisible(true);
                this.dispose();
                break;
            }
            case 4:
            {
                JOptionPane.showMessageDialog(this, "Đăng nhập thành công","thành công",JOptionPane.INFORMATION_MESSAGE);
                quantrivien a = new  quantrivien(user_id);
                a.setVisible(true);
                this.dispose();
                break;
            }
            case 0:
                txtDangnhap.setText("");
                txtPass.setText("");
                break;
        }
    }//GEN-LAST:event_jButtondangnhapActionPerformed

    private void check_showActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check_showActionPerformed
        if (check_show.isSelected()) {
                    txtPass.setEchoChar((char) 0);
                } else {
                    txtPass.setEchoChar('•');
                }
    }//GEN-LAST:event_check_showActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dangnhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dangnhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dangnhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dangnhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dangnhap().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox check_show;
    private javax.swing.JButton jButtondangnhap;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtDangnhap;
    private javax.swing.JPasswordField txtPass;
    // End of variables declaration//GEN-END:variables
}
